package org.kabling.teaming.install.client.leftnav;

public enum LeftNavItemType
{
	LUCENE,
	WEBDAV_AUTHENTICATION,
	JAVA_JDK,
	DATABASE,
	NETWORK,
	CLUSTERING,
	OUTBOUND_EMAIL,
	REQUESTS_AND_CONNECTIONS,
	WEB_SERVICES,
	NOVELL_ACCESS_MANAGER,
	INBOUND_EMAIL,
	IMPORT_EXPORT,
	LICENSE_INFORMATION,
	ENVIRONMENT
}
