use sitescape;
alter table SS_ZoneConfig add column mobileAccessEnabled bit;
alter table SS_AuditTrail add column deletedFolderEntryFamily varchar(32);
alter table SS_FolderEntries add column preDeleted bit;
alter table SS_FolderEntries add column preDeletedWhen bigint;
alter table SS_FolderEntries add column preDeletedBy bigint;
alter table SS_Forums add column preDeleted bit;
alter table SS_Forums add column preDeletedWhen bigint;
alter table SS_Forums add column preDeletedBy bigint;
alter table SS_Attachments add column relevanceUUID varchar(256);
alter table SS_Principals add column diskSpaceUsed bigint;
alter table SS_Principals add column diskQuota bigint;
alter table SS_Principals add column maxGroupsQuota bigint;
alter table SS_ZoneConfig add column diskQuotasEnabled bit;
alter table SS_ZoneConfig add column diskQuotaUserDefault integer;
alter table SS_ZoneConfig add column diskQuotasHighwaterPercentage integer;
