/**
 * Copyright (c) 1998-2014 Novell, Inc. and its licensors. All rights reserved.
 * 
 * This work is governed by the Common Public Attribution License Version 1.0 (the
 * "CPAL"); you may not use this file except in compliance with the CPAL. You may
 * obtain a copy of the CPAL at http://www.opensource.org/licenses/cpal_1.0. The
 * CPAL is based on the Mozilla Public License Version 1.1 but Sections 14 and 15
 * have been added to cover use of software over a computer network and provide
 * for limited attribution for the Original Developer. In addition, Exhibit A has
 * been modified to be consistent with Exhibit B.
 * 
 * Software distributed under the CPAL is distributed on an "AS IS" basis, WITHOUT
 * WARRANTY OF ANY KIND, either express or implied. See the CPAL for the specific
 * language governing rights and limitations under the CPAL.
 * 
 * The Original Code is ICEcore, now called Kablink. The Original Developer is
 * Novell, Inc. All portions of the code written by Novell, Inc. are Copyright
 * (c) 1998-2014 Novell, Inc. All Rights Reserved.
 * 
 * Attribution Information:
 * Attribution Copyright Notice: Copyright (c) 1998-2014 Novell, Inc. All Rights Reserved.
 * Attribution Phrase (not exceeding 10 words): [Powered by Kablink]
 * Attribution URL: [www.kablink.org]
 * Graphic Image as provided in the Covered Code
 * [ssf/images/pics/powered_by_icecore.png].
 * Display of Attribution Information is required in Larger Works which are
 * defined in the CPAL as a work which combines Covered Code or portions thereof
 * with code not governed by the terms of the CPAL.
 * 
 * NOVELL and the Novell logo are registered trademarks and Kablink and the
 * Kablink logos are trademarks of Novell, Inc.
 */
package org.kablink.teaming.samples.wsclient;

import java.io.File;
import java.io.IOException;
import java.rmi.RemoteException;
import java.util.Calendar;
import java.util.Date;
import java.util.List;

import javax.xml.rpc.ServiceException;

import org.apache.axis.EngineConfiguration;

import org.dom4j.Document;
import org.dom4j.DocumentException;
import org.dom4j.DocumentHelper;
import org.dom4j.Element;
import org.dom4j.io.OutputFormat;
import org.dom4j.io.XMLWriter;

import org.kablink.teaming.client.ws.WebServiceClientUtil;
import org.kablink.teaming.client.ws.TeamingServiceSoapBindingStub;
import org.kablink.teaming.client.ws.TeamingServiceSoapServiceLocator;
import org.kablink.teaming.client.ws.model.*;
import org.kablink.teaming.web.util.BuiltInUsersHelper;
import org.kablink.util.search.Constants;
import org.kablink.util.search.Criteria;

import static org.kablink.util.search.Restrictions.*;

/**
 * This WS client program uses JAX-RPC compliant client binding classes 
 * generated by Axis' WSDL2Java tool.
 * 
 * @author jong
 */
@SuppressWarnings({"unchecked", "unused"})
public class TeamingServiceClientWithStub {
	private static final String TEAMING_SERVICE_ADDRESS_WSS 	= "http://localhost:8080/ssf/ws/TeamingServiceV1";
	private static final String TEAMING_SERVICE_ADDRESS_BASIC 	= "http://localhost:8080/ssr/secure/ws/TeamingServiceV1";
	private static final String TEAMING_SERVICE_ADDRESS_TOKEN   = "http://localhost:8080/ssr/token/ws/TeamingServiceV1";

	  private static final String USERNAME = "admin";
	  private static final String PASSWORD = "admin";
	//private static final String USERNAME = "synchagent";
	//private static final String PASSWORD = "test";
	
	public static void main(String[] args) throws Exception {
		FolderEntry entry;
		
		/*
		User user = getTestUser();
		System.out.println("Test user name: " + user.getName());
		changeUserPassword(user.getId(), "test", "newtest");
		System.out.println("Password changed");
		*/
		
		//copyFileFromUserToEntry();
		
		//copyFolderEntry(177, 1287, false);
		//copyFolderEntry(177, 1288, true);
		
		//checkBinderSubscriptions(41);
		//addMicroBlog();
		
		//searchFolderEntriesAndNoReplies();
		//searchFolderEntriesAndReplies();
		//getAllRepliesToSpecificEntry();

		//testApplicationScopedToken();
		
		//calendarSync();
		//checkUsers();
		//checkGroups();
		//checkBinder();
		//checkEntry();
		//getFolderEntryWSSecurity(47, true);
		//getFolderEntry(6, false);
		
		// Test add
		//entry = getFolderEntry(80, false);
		//addFolderEntryByCopying(entry);
		
		// Test modify
		//entry = getFolderEntry(80, false);
		//modifyFolderEntry(entry);
		
		// Test delete
		//deleteFolderEntry(47);
		
		// Upload files
		//uploadFolderEntryFiles(85);
		
		//getFolderEntries(44, 0, 0);
		
		//getPrincipal(1);
		
		//getPrincipals(2, 5);
		
		//fetchTaskEntriesModifiedBetweenTwoDates();
		
		//fetchCalendarEntriesModifiedBetweenTwoDates();
		
		//fetchCalendarEntriesCreatedOrModifiedOrEventDatedBetweenTwoDates();
		
		//addFileEntry();
		
		//addDiscussionEntry();
		
		// addTaskEntry();
		
		//getFunctionMembership();
		//setFunctionMembership();
		
/*		try {
			getEntryFileVersions(9, "debug.doc");
		}
		catch(Exception e) {
			e.printStackTrace();
		}
		try {
			getEntryFileVersions(9, "non-existing.file");
		}
		catch(Exception e) {
			e.printStackTrace();
		}
		try {
			getEntryFileVersions(99999, "non-existing.entry");
		}
		catch(Exception e) {
			e.printStackTrace();
		}
*/
		
		//getMovedEntries();
		
		//getDeletedAndRestoredEntries();
		
		//addDicsussionEntryWithChineseInTitle();
		
		//downloadSameFileMultipleTimes();
		
		//addBlogEntryWithAttachment();
		
		//getTopWorkspaceIdRepeatedlyUsingMultipleThreads();

	}
	
	public static void addMicroBlog() throws Exception {
		TeamingServiceSoapBindingStub stub = getStubBasic();
		
		Long id = stub.folder_addMicroBlog(null, "More efficient blog!");
				
		if(id != null)
			System.out.println("Successfully added a micro blog entry. The id is " + id);
		else
			System.out.println("Could not add micro blog entry");
	}
	
	public static void addMicroBlog_OldWay_ThisDoesNotWork() throws Exception {
		TeamingServiceSoapBindingStub stub = getStubBasic();

		User admin = stub.profile_getUserByName(null, USERNAME, false);
		DefinitionBrief db = stub.definition_getDefinitionByName(null, "_miniblog_entry");
		FolderEntry entry = new FolderEntry();
		entry.setDefinitionId(db.getId());
		entry.setParentBinderId(admin.getMiniBlogId());
		entry.setTitle(new java.util.Date().toString());
		Description desc = new Description();
		desc.setFormat(1);
		desc.setText("My Status Update");
		entry.setDescription(desc);
		
		long id = stub.folder_addEntry(null, entry, null);
				
		System.out.println("Successfully added a micro blog entry. The id is " + id);
	}
	
	private static void callGetTeamsUsingToken(TeamingServiceSoapBindingStub regularStub, long applicationId, long userId, long delayInSecond) throws Exception {
		try {
			// Obtain an application-scoped token on behalf of the user. 
			// This call is made through the regular web services endpoint.
			String token = regularStub.admin_getApplicationScopedToken(null, applicationId, userId);
			try {
				// If you're here, the request was successful.
				System.out.println("Obtained token=" + token + " for application=" + applicationId + " user=" + userId);
				
				if(delayInSecond > 0) {
					System.out.println("Sleeping for " + delayInSecond + " seconds");
					Thread.sleep(delayInSecond*1000);
				}
				
				// Invoke search_getTeams() web services operation using the token obtained above.
				// This call must be made through the endpoint set up for token-based web services.
				TeamingServiceSoapServiceLocator locator = new TeamingServiceSoapServiceLocator();
				locator.setTeamingServiceEndpointAddress(TEAMING_SERVICE_ADDRESS_TOKEN);
				TeamingServiceSoapBindingStub tokenBasedStub = (TeamingServiceSoapBindingStub) locator.getTeamingService();
				TeamCollection tc = tokenBasedStub.search_getTeams(token);
				System.out.println("Successfully invoked getTeams() operation with result size = " + tc.getTeams().length);
			}
			finally {
				// Destroy the token. Again, this call is made through the regular web services endpoint.
				regularStub.admin_destroyApplicationScopedToken(null, token);		
				System.out.println("Destroyed token: " + token);
			}
		}
		catch(Exception e) {
			System.out.println(e.toString());
		}
	}
	
	public static void testApplicationScopedToken() throws Exception {
		TeamingServiceSoapBindingStub stub = getStubBasic();

		// Non-existing application ID
		callGetTeamsUsingToken(stub, 12345, 8, 0);
		
		// Non-existing user ID
		callGetTeamsUsingToken(stub, 57, 888, 0);
		
		// Existing application ID and user ID
		callGetTeamsUsingToken(stub, 57, 7, 0);
		
		// Existing application ID and user ID (with 10 second delay between obtaining and using token)
		callGetTeamsUsingToken(stub, 57, 7, 10);
		
		// Existing application ID and user ID
		callGetTeamsUsingToken(stub, 57, 7, 2);
	}
	
	public static void fetchTaskEntriesModifiedBetweenTwoDates() throws Exception {
		TeamingServiceSoapBindingStub stub = getStubBasic();

		// Create search criteria
		Criteria crit = new Criteria()
		.add(eq(Constants.DOC_TYPE_FIELD, Constants.DOC_TYPE_ENTRY)) // only entries, not binders or attachments
		.add(eq(Constants.FAMILY_FIELD, Constants.FAMILY_FIELD_TASK)) // only task family
		.add(eq(Constants.ENTRY_TYPE_FIELD, Constants.ENTRY_TYPE_ENTRY)) // only entries, not replied
		.add(between(Constants.MODIFICATION_DATE_FIELD, "20100801000000", "20110931235959")) // modification time should fall in this range (inclusive)
		.add(not().add(eq("status","s3"))) // only those tasks not yet completed
		;
		
		System.out.println("Here's the search string in XML");
		System.out.println(crit.toQuery().asXML());
		// The above search string should print like this.
		// <QUERY><AND><FIELD fieldname="_family" exactphrase="TRUE"><TERMS>task</TERMS></FIELD><FIELD fieldname="_entryType" exactphrase="TRUE"><TERMS>entry</TERMS></FIELD><RANGE fieldname="_modificationDate" inclusive="TRUE"><START>20100801000000</START><FINISH>20100931235959</FINISH></RANGE><NOT><FIELD fieldname="status" exactphrase="TRUE"><TERMS>s3</TERMS></FIELD></NOT></AND></QUERY>
 
		// Execute the search against a Teaming server and print the result.
		Document xmlResults = DocumentHelper.parseText(stub.search_search(null, crit.toQuery().asXML(), 0, 100));
		prettyPrintXML(xmlResults);
    	List<Element> entries = xmlResults.getRootElement().selectNodes("/searchResults/entry");
    	if (entries == null || entries.isEmpty()) {
    		System.out.println("No matching entries");
    	}
    	for (Element eEle:entries) {
    		Long id = Long.valueOf(eEle.attributeValue("id"));
    		String title = eEle.attributeValue("title");
    		FolderEntry entry = stub.folder_getEntry(null, id, false, false);
    		System.out.println(id + " [" + title + "]");
    	}
	}

	public static void fetchCalendarEntriesModifiedBetweenTwoDates() throws Exception {
		TeamingServiceSoapBindingStub stub = getStubBasic();

		// Create search criteria
		Criteria crit = new Criteria()
		.add(eq(Constants.DOC_TYPE_FIELD, Constants.DOC_TYPE_ENTRY)) // only entries, not binders or attachments
		.add(eq(Constants.FAMILY_FIELD, Constants.FAMILY_FIELD_CALENDAR)) // only calendar family
		.add(eq(Constants.ENTRY_TYPE_FIELD, Constants.ENTRY_TYPE_ENTRY)) // only entries, not replied
		.add(between(Constants.MODIFICATION_DATE_FIELD, "20110401000000", "20111031235959")) // modification time should fall in this range (inclusive)
		.add(in(Constants.BINDER_ID_FIELD, new String[] {"43", "148"}));
		
		System.out.println("Here's the search string in XML");
		System.out.println(crit.toQuery().asXML());
		// The above search string should print like this.
		// <QUERY><AND><FIELD fieldname="_family" exactphrase="TRUE"><TERMS>calendar</TERMS></FIELD><FIELD fieldname="_entryType" exactphrase="TRUE"><TERMS>entry</TERMS></FIELD><RANGE fieldname="_modificationDate" inclusive="TRUE"><START>20100801000000</START><FINISH>20101031235959</FINISH></RANGE><OR><FIELD fieldname="_binderId" exactphrase="TRUE"><TERMS>43</TERMS></FIELD><FIELD fieldname="_binderId" exactphrase="TRUE"><TERMS>148</TERMS></FIELD></OR></AND></QUERY>
 
		// Execute the search against a Teaming server and print the result.
		FolderEntryCollection coll = stub.search_getFolderEntries(null, crit.toQuery().asXML(), 0, 100);
		
    	FolderEntryBrief[] entries = coll.getEntries();
    	System.out.println("Result size: " + entries.length);
    	for(int i = 0; i < entries.length; i++) {
    		FolderEntryBrief entry = entries[i];
    		System.out.println("id=" + entry.getId() + ", binderId=" + entry.getBinderId() + 
    				", docNumber=" + entry.getDocNumber() + ", docLevel=" + entry.getDocLevel() + 
    				", title=" + entry.getTitle() + ", permalink=" + entry.getPermaLink() +
    				", creation time=" + entry.getCreation().getDate().getTime() +
    				", creation timezone=" + entry.getCreation().getDate().getTimeZone() +
    				", modification time=" + entry.getModification().getDate().getTime() +
    				", modification timezone=" + entry.getModification().getDate().getTimeZone());
    	}
	}
	
	public static void fetchCalendarEntriesCreatedOrModifiedOrEventDatedBetweenTwoDates() throws Exception {
		TeamingServiceSoapBindingStub stub = getStubBasic();
		
		String beginDate = "20101101000000";
		String endDate   = "20101201000000";

		// Create search criteria
		Criteria crit = new Criteria()
		.add(eq(Constants.DOC_TYPE_FIELD, Constants.DOC_TYPE_ENTRY)) // only entries, not binders or attachments
		.add(eq(Constants.ENTRY_TYPE_FIELD, Constants.ENTRY_TYPE_ENTRY)) // only top-level entries, not replies
		.add(eq(Constants.FAMILY_FIELD, Constants.FAMILY_FIELD_CALENDAR)) // only calendar family
		.add(disjunction().
				add(between(Constants.CREATION_DATE_FIELD, beginDate, endDate)). // creation date falls in this range (inclusive)
				add(between(Constants.MODIFICATION_DATE_FIELD, beginDate, endDate)). // modification date falls in this range (inclusive)
				add(between(Constants.EVENT_DATES_FIELD , beginDate, endDate))) // at least one event date falls in this range (inclusive)
		.add(in(Constants.BINDER_ID_FIELD, new String[] {"43", "148"}));
		
		System.out.println("Here's the search string in XML");
		System.out.println(crit.toQuery().asXML());
		// The above search string should print like this.
		// <QUERY><AND><FIELD fieldname="_docType" exactphrase="TRUE"><TERMS>entry</TERMS></FIELD><FIELD fieldname="_entryType" exactphrase="TRUE"><TERMS>entry</TERMS></FIELD><FIELD fieldname="_family" exactphrase="TRUE"><TERMS>calendar</TERMS></FIELD><OR><RANGE fieldname="_creationDate" inclusive="TRUE"><START>20101101000000</START><FINISH>20101201000000</FINISH></RANGE><RANGE fieldname="_modificationDate"inclusive="TRUE"><START>20101101000000</START><FINISH>20101201000000</FINISH></RANGE><RANGE fieldname="_eventDates" inclusive="TRUE"><START>20101101000000</START><FINISH>20101201000000</FINISH></RANGE></OR><OR><FIELD fieldname="_binderId" exactphrase="TRUE"><TERMS>43</TERMS></FIELD><FIELD fieldname="_binderId" exactphrase="TRUE"><TERMS>148</TERMS></FIELD></OR></AND></QUERY>
		 
		// Execute the search against a Teaming server and print the result.
		FolderEntryCollection coll = stub.search_getFolderEntries(null, crit.toQuery().asXML(), 0, 100);
		
    	FolderEntryBrief[] entries = coll.getEntries();
    	System.out.println("Result size: " + entries.length);
    	for(int i = 0; i < entries.length; i++) {
    		FolderEntryBrief entry = entries[i];
    		System.out.println("id=" + entry.getId() + ", binderId=" + entry.getBinderId() + ", docNumber=" + entry.getDocNumber() + ", docLevel=" + entry.getDocLevel() + ", title=" + entry.getTitle());
    	}
	}
	
	public static void calendarSync() throws Exception {
		TeamingServiceSoapBindingStub stub = getStubBasic();

		User testUser = stub.profile_getUserByName(null, "kelly", false);
		Long wsId = testUser.getWorkspaceId();
		
		//search for calendar folder
    	Criteria crit = new Criteria()
			.add(eq(Constants.BINDERS_PARENT_ID_FIELD, wsId.toString())) //child 
			.add(eq(Constants.FAMILY_FIELD, Constants.FAMILY_FIELD_CALENDAR))
			.add(eq(Constants.ENTITY_FIELD, "folder"));
    	
    	Document xmlResults = DocumentHelper.parseText(stub.search_search(null, crit.toQuery().asXML(), 0, -1));
    	//grab the first calendar
    	List<Element> binders = xmlResults.getRootElement().selectNodes("/searchResults/binder");
    	if (binders == null || binders.isEmpty()) {
    		System.out.println("User calendar not found");
    		return;
    	}
    	Element calEle =  binders.get(0);
    	Long calId = Long.valueOf(calEle.attributeValue("id"));
    	
    	crit = new Criteria()
    		.add(eq(Constants.BINDER_ID_FIELD, calId.toString()))
    		.add(eq(Constants.ENTRY_TYPE_FIELD, Constants.ENTRY_TYPE_ENTRY));//no replies
    	
    	//now search for calendar entries
    	xmlResults = DocumentHelper.parseText(stub.search_search(null, crit.toQuery().asXML(), 0, 100));
    	List<Element> entries = xmlResults.getRootElement().selectNodes("/searchResults/entry");
    	if (entries == null || entries.isEmpty()) {
    		System.out.println("Calendar empty");
    		return;
    	}
    	for (Element eEle:entries) {
    		Long id = Long.valueOf(eEle.attributeValue("id"));
    		FolderEntry entry = stub.folder_getEntry(null, id, true, false);
    		WebServiceClientUtil.extractFiles(stub, new File("icals"));
    		System.out.println(entry.getTitle());
    	}
	}
	public static void searchFolderEntriesAndNoReplies() throws Exception {
		TeamingServiceSoapBindingStub stub = getStubBasic();
		
		// Search for all folder entries with the word "test" in entry title.
    	Criteria crit = new Criteria()
			.add(like(Constants.TITLE_FIELD, "test"))
			.add(eq(Constants.ENTRY_TYPE_FIELD, Constants.ENTRY_TYPE_ENTRY));
	
		FolderEntryCollection coll = stub.search_getFolderEntries(null, crit.toQuery().asXML(), 0, -1);
    	FolderEntryBrief[] entries = coll.getEntries();
    	System.out.println("Result size: " + entries.length);
    	for(int i = 0; i < entries.length; i++) {
    		FolderEntryBrief entry = entries[i];
    		System.out.println("id=" + entry.getId() + ", binderId=" + entry.getBinderId() + ", docNumber=" + entry.getDocNumber() + ", docLevel=" + entry.getDocLevel() + ", title=" + entry.getTitle());
    	}
	}
	public static void searchFolderEntriesAndReplies() throws Exception {
		TeamingServiceSoapBindingStub stub = getStubBasic();
		
		// Search for all folder entries and replies with the word "test" in any text field.
    	Criteria crit = new Criteria()
			.add(like(null, "test"));
	
		FolderEntryCollection coll = stub.search_getFolderEntries(null, crit.toQuery().asXML(), 0, -1);
    	FolderEntryBrief[] entries = coll.getEntries();
    	System.out.println("Result size: " + entries.length);
    	for(int i = 0; i < entries.length; i++) {
    		FolderEntryBrief entry = entries[i];
    		System.out.println("id=" + entry.getId() + ", binderId=" + entry.getBinderId() + ", docNumber=" + entry.getDocNumber() + ", docLevel=" + entry.getDocLevel() + ", title=" + entry.getTitle());
    	}
	}
	public static void getAllRepliesToSpecificEntry() throws Exception {
		TeamingServiceSoapBindingStub stub = getStubBasic();
		
		// Fetch all replies to a specific entry.
    	Criteria crit = new Criteria()
			.add(eq(Constants.ENTRY_TYPE_FIELD, Constants.ENTRY_TYPE_REPLY))
			.add(eq(Constants.ENTRY_TOP_ENTRY_ID_FIELD, "129"));
	
		FolderEntryCollection coll = stub.search_getFolderEntries(null, crit.toQuery().asXML(), 0, -1);
    	FolderEntryBrief[] entries = coll.getEntries();
    	System.out.println("Result size: " + entries.length);
    	for(int i = 0; i < entries.length; i++) {
    		FolderEntryBrief entry = entries[i];
    		System.out.println("id=" + entry.getId() + ", binderId=" + entry.getBinderId() + ", docNumber=" + entry.getDocNumber() + ", docLevel=" + entry.getDocLevel() + ", title=" + entry.getTitle());
    	}
	}
	public static void checkTags(long binderId) throws Exception {
		TeamingServiceSoapBindingStub stub = getStubBasic();

		Tag[] tags = setupTags(binderId);
		for (int i=0; i<tags.length; ++i) {
			stub.binder_setTag(null, tags[i]);			
		}
		tags = stub.binder_getTags(null, binderId);
		validateTags(tags);
		stub.binder_deleteTag(null, binderId, tags[0].getId());
		tags = stub.binder_getTags(null, binderId);
		if (tags.length != 1) System.out.println("Number of tags expected=1, actual=" + tags.length);
		System.out.println("End tags");
		
	}
	public static void checkEntryTags(long entryId) throws Exception {
		TeamingServiceSoapBindingStub stub = getStubBasic();

		Tag[] tags = setupTags(entryId);
		for (int i=0; i<tags.length; ++i) {
			stub.folder_setEntryTag(null, tags[i]);			
		}
		tags = stub.folder_getEntryTags(null, entryId);
		validateTags(tags);
		stub.folder_deleteEntryTag(null, entryId, tags[0].getId());
		tags = stub.folder_getEntryTags(null, entryId);
		if (tags.length != 1) System.out.println("Number of tags expected=1, actual=" + tags.length);
		System.out.println("End tags");
		
	}
	private static Tag[] setupTags(long entityId) {
		Tag tag1 = new Tag();
		tag1.setEntityId(entityId);
		tag1.setName("tag1");
		Tag tag2 = new Tag();
		tag2.setName("tag2");
		tag2.setEntityId(entityId);
		return new Tag[] {tag1, tag2};
	}
	private static void validateTags(Tag[] tags) {
		if (tags.length != 2) System.out.println("Number of tags expected=2, actual=" + tags.length);
		for (int i=0; i<tags.length; ++i) {			
			if (!tags[i].getName().equals("tag1") && !tags[i].getName().equals("tag2")) {
				System.out.println("Unexpected tag=" + tags[i].getName());
			}
		}		
	}
	public static void checkBinder() throws Exception {
		TeamingServiceSoapBindingStub stub = getStubBasic();

		Binder testFolder1 = getTestFolder("MyTestingFolder");
		Binder testFolder2 = new Binder();
		testFolder2.setTitle("MyTestingFolder3");
		testFolder2.setDefinitionId(testFolder1.getDefinitionId());
		testFolder2.setParentBinderId(testFolder1.getId());
		try {
			stub.binder_indexBinder(null, testFolder1.getId());
			stub.binder_indexTree(null, testFolder1.getId());
			//add new binder without config
			long testFolder2Id = stub.binder_addBinder(null, testFolder2);
			checkTags(testFolder1.getId());
			checkBinderSubscriptions(testFolder1.getId());
			//move new binder to under global
			stub.binder_moveBinder(null, testFolder2Id, testFolder1.getParentBinderId());
			//copy binder back to under test folder
			long testFolder3Id = stub.binder_copyBinder(null, testFolder2Id, testFolder1.getId(), true);			
			stub.binder_deleteBinder(null, testFolder2Id, true);
			Binder testFolder3 = modifyBinder(stub.binder_getBinder(null, testFolder3Id, false));
			testFolder3 = uploadBinderFiles(testFolder3);
		} finally {
			stub.binder_deleteBinder(null, testFolder1.getId(), true);
		}
	}
	public static void checkEntrySubscriptions(long entryId) throws Exception {
		TeamingServiceSoapBindingStub stub = getStubBasic();

		Subscription subscription = setupSubscription(entryId);
		stub.folder_setSubscription(null, entryId, subscription);
		subscription = stub.folder_getSubscription(null, entryId);
		validateSubscription(subscription);
	}
	public static void checkBinderSubscriptions(long binderId) throws Exception {
		TeamingServiceSoapBindingStub stub = getStubBasic();

		Subscription subscription = setupSubscription(binderId);
		stub.binder_setSubscription(null, binderId, subscription);
		subscription = stub.binder_getSubscription(null, binderId);
		validateSubscription(subscription);
	}

	private static Subscription setupSubscription(long entityId) {
		SubscriptionStyle style3 = new SubscriptionStyle();
		SubscriptionStyle style2 = new SubscriptionStyle();
		style3.setStyle(3);
		style3.setEmailTypes(new String[] {"_primary","_mobile"});
		style2.setStyle(2);
		style2.setEmailTypes(new String[] {"_text","_mobile"});
		Subscription subscription = new Subscription();
		subscription.setStyles(new SubscriptionStyle[] {style3, style2});
		return subscription;
	}
	private static void validateSubscription(Subscription subscription) {
		SubscriptionStyle[] styles = subscription.getStyles();
		if (styles.length != 2) System.out.println("Expect 2 subscriptions styles, got " + styles.length);
		for (int i=0; i<styles.length; ++i) {
			String [] emails = styles[i].getEmailTypes();
			if (emails.length != 2) System.out.println("Expect 2 emailTypes, got " + emails.length);
			if (styles[i].getStyle() == 1) {
				if (emails[0].equals("_primary") || emails[0].equals("_mobile")) continue;
				if (emails[1].equals("_primary") || emails[1].equals("_mobile")) continue;
				System.out.println("Unexpected emailTypes " + emails);
				
			} else if (styles[i].getStyle() == 2) {
				if (emails[0].equals("_text") || emails[0].equals("_mobile")) continue;
				if (emails[1].equals("_text") || emails[1].equals("_mobile")) continue;				
				System.out.println("Unexpected emailTypes " + emails);
			}			
		}
		
	}
	
	public static void addFileEntry() throws Exception {
		TeamingServiceSoapBindingStub stub = getStubBasic();
		FolderEntry testEntry = new FolderEntry();
		// Do not add title!!!
		testEntry.setDescription(new Description(1,"Creating a file entry through web services"));
		testEntry.setParentBinderId(new Long(518));
		long testEntryId = stub.folder_addEntry(null, testEntry, null);
		System.out.println("Successfully created an empty file entry with ID = " + testEntryId);
		String fileText = "Wow, this works!!";
		stub.folder_uploadFileAsByteArray(null, testEntryId, null, "what-the.txt", fileText.getBytes());
		System.out.println("Successfully uploaded primary file");
	}
	
	public static void addDicsussionEntryWithChineseInTitle() throws Exception {
		TeamingServiceSoapBindingStub stub = getStubBasic();
		FolderEntry testEntry = new FolderEntry();
		// Option 1 - This is the original Chinese text. To embed this literal Chinese characters 
		// in Java source code, the .java file must be saved in UTF-8 encoding. In such case, you
		// must also specify UTF-8 as encoding when compiling the source file into class file.
		// When using this option, the underlying web services framework (Axis 1.4) will correctly
		// encode the input text using numeric character reference as specified by the standard.
		//String text = "下記.txt";
		// Option 2 - Assign Chinese string to a variable by using Unicode code value representation 
		// instead of the above literal characters. This way, you can save this .java file in 
		// more common ISO8859-1 encoding without losing the Chinese character values. 
		// The underlying web services framework will correctly encode these Unicode characters 
		// using numeric character reference representation before placing them into SOAP payload.
		String text = "\u4e0b\u8a18\u002e\u0074\u0078\u0074";
		// Option 3 - The application (this code) encodes the text in numeric character reference 
		// and passes the result to the underlying framework. This will work ONLY IF the underlying
		// framework does NOT perform additional encoding on the provided input string. Otherwise,
		// the original string can be double encoded resulting in unexpected behavior.
		//String text = "&#x4E0B;&#x8A18;.txt";
		byte[] ba = text.getBytes("UTF-8");
		for(byte b:ba) {
			int i = b & 0xFF;
			System.out.print(Integer.toHexString(i) + " ");
		}
		System.out.println();
		for(int i=0; i < text.length(); i++) {
			int c = text.codePointAt(i);
			System.out.print(Integer.toHexString(c) + " ");
		}
		System.out.println();
		testEntry.setTitle(text);
		testEntry.setDescription(new Description(1,text));
		testEntry.setParentBinderId(new Long(48));
		long testEntryId = stub.folder_addEntry(null, testEntry, null);
		System.out.println("Successfully created a discussion entry with ID = " + testEntryId);
		
		// Attach a file to the entry. This file contains Chinese in both filename and content.
		// The following two statements are equivalent.
		//stub.folder_uploadFileAsByteArray(null, testEntryId, null, "下記.txt", "下記".getBytes("UTF-8"));
		stub.folder_uploadFileAsByteArray(null, testEntryId, null, text, "\u4e0b\u8a18".getBytes("UTF-8"));
		System.out.println("Successfully uploaded primary file with Chinese in both filename and content");
	}
	
	public static void addDiscussionEntry() throws Exception {
		TeamingServiceSoapBindingStub stub = getStubBasic();
		FolderEntry testEntry = new FolderEntry();
		testEntry.setTitle("Created from web services");
		testEntry.setDescription(new Description(1,"Setting creator and creation time programmtically"));
		testEntry.setParentBinderId(new Long(251));
	    Calendar cal = Calendar.getInstance();
	    cal.setTimeInMillis(cal.getTimeInMillis() - 100000000);
	    Timestamp ts = new Timestamp(cal,"user1", null);
	    testEntry.setCreation(ts);
		long testEntryId = stub.folder_addEntry(null, testEntry, null);
		System.out.println("Successfully created a discussion entry with ID = " + testEntryId);
	}
	
	public static void addBlogEntryWithAttachment() throws Exception {
		TeamingServiceSoapBindingStub stub = getStubBasic();
		FolderEntry blogEntry = new FolderEntry();
		blogEntry.setTitle("Blog entry created through web services");
		blogEntry.setDescription(new Description(1,"This blog entry has a file attachment"));
		Long blogFolderId = 42L;
		blogEntry.setParentBinderId(blogFolderId);
		long blogEntryId = stub.folder_addEntry(null, blogEntry, null);
		System.out.println("Successfully created a blog entry with ID = " + blogEntryId);
		String fileName = "test-file.txt";
		String fileContent = "Let's see if we can upload this file";
		stub.folder_uploadFileAsByteArray(null, blogEntryId, null, fileName, fileContent.getBytes("UTF-8"));
		System.out.println("Successfully attached a file to the entry");
	}
	
	public static void checkEntry()  throws Exception {
		TeamingServiceSoapBindingStub stub = getStubBasic();

		Binder testFolder = getTestFolder("MyTestingFolder");
		try {
			FolderEntry testEntry = new FolderEntry();
			testEntry.setDescription(new Description(1,"This entry was added by web-services.  Workflow is next"));
			testEntry.setParentBinderId(testFolder.getId());
			testEntry.setTitle("Added by web-services");
			File file = new File("C:/junk/junk1/debug.txt");		
			WebServiceClientUtil.attachFile(stub, file);
			long testEntryId = stub.folder_addEntry(null, testEntry, "debug1.txt");
			testEntry = stub.folder_getEntry(null, testEntryId, true, false);
			System.out.println("(WSS) Number of attachments downloaded = " + WebServiceClientUtil.extractFiles(stub, null));
			checkWorkflow(testEntryId);
			checkEntryTags(testEntryId);
			checkEntrySubscriptions(testEntryId);
			stub.folder_setRating(null, testEntryId, 4);
			testEntry = stub.folder_getEntry(null, testEntryId, false, false);
			if (!testEntry.getAverageRating().getAverageRating().equals(Double.valueOf(4))) System.out.println("Error unexpected average ");
			file = new File("C:/junk/junk1/debug.txt");		
			WebServiceClientUtil.attachFile(stub, file);
			stub.folder_uploadFile(null, testEntry.getId(), "", "debug2.txt");
			testEntry = stub.folder_getEntry(null, testEntryId, true, false);
			System.out.println("(WSS) Number of attachments downloaded = " + WebServiceClientUtil.extractFiles(stub, null));

			long copiedEntryId = stub.folder_copyEntry(null, testEntryId, testFolder.getId());
			Binder testFolder2 = getTestFolder("MyTestingFolder2");
			stub.folder_moveEntry(null, copiedEntryId, testFolder2.getId());
			FolderEntry movedEntry = stub.folder_getEntry(null, copiedEntryId, false, false);
			if (!movedEntry.getParentBinderId().equals(Long.valueOf(testFolder2.getId()))) System.out.println("Error - entry not moved");
			stub.binder_deleteBinder(null, testFolder2.getId(), true);
			stub.folder_deleteEntry(null, testEntryId);
		} finally {
			stub.binder_deleteBinder(null, testFolder.getId(), true);
		}
		
	}
	public static void checkWorkflow(long entryId)  throws Exception {
		TeamingServiceSoapBindingStub stub = getStubBasic();

		FolderEntry	entry = stub.folder_getEntry(null, entryId, false, false);
		DefinitionBrief def = stub.definition_getLocalDefinitionByName(null, entry.getParentBinderId(), "testworkflow", true);
		stub.folder_addEntryWorkflow(null, entryId, def.getId());
		entry = stub.folder_getEntry(null, entryId, false, false);
		Workflow[] wfs = entry.getWorkflows();
		boolean found = false;
		for (int i=0; i<wfs.length; ++i) {
			if ("state1".equals(wfs[i].getState())) {
				found=true;
				break;
			}
		}
		if (!found) System.out.println("Error, expecting state1");
		stub.folder_modifyWorkflowState(null, entryId, wfs[0].getTokenId(), "state2");
		entry = stub.folder_getEntry(null, entryId, false, false);
		wfs = entry.getWorkflows();
		found = false;
		for (int i=0; i<wfs.length; ++i) {
			if ("state2".equals(wfs[i].getState())) {
				found=true;
				break;
			}
		}
		if (!found) System.out.println("Error, expecting state2");
		stub.folder_setWorkflowResponse(null,  entryId, wfs[0].getTokenId(), "dayquestion", "sundayresponse");
		entry = stub.folder_getEntry(null, entryId, false, false);
		wfs	= entry.getWorkflows();
		found = false;
		for (int i=0; i<wfs.length; ++i) {
			if ("itssunday".equals(wfs[i].getState())) {
				WorkflowResponse[] wfr = wfs[i].getResponses();
				if (wfr.length == 1) {
					if ("dayquestion".equals(wfr[0].getQuestion()) &&
							"sundayresponse".equals(wfr[0].getResponse())) {
						found=true;
						break;
						
					}
				}
			}
		}
		if (!found) System.out.println("Error, expecting itssunday with response sundayresponse");
		int count = wfs.length;
		stub.folder_deleteEntryWorkflow(null,  entryId, def.getId());
		entry = stub.folder_getEntry(null,  entryId, false, false);
		wfs = entry.getWorkflows();
		if (wfs.length != count-1) System.out.println("Error workflow not deleted");
		
	}
	
	public static FolderEntry getFolderEntryWSSecurity(long entryId, boolean includeAttachments) throws Exception {
		// Use WS-Security
		TeamingServiceSoapBindingStub stub = getStubWSS();

		FolderEntry entry = stub.folder_getEntry(null, entryId, includeAttachments, false);
		
		System.out.println("(WSS) Entry title: " + entry.getTitle());
		
		System.out.println("(WSS) Number of attachments downloaded = " + WebServiceClientUtil.extractFiles(stub, null));
		
		return entry;
	}

	public static FolderEntry getFolderEntry(long entryId, boolean includeAttachments) throws Exception {
		TeamingServiceSoapBindingStub stub = getStubBasic();

		FolderEntry entry = stub.folder_getEntry(null, entryId, includeAttachments, false);
		
		System.out.println("Entry title: " + entry.getTitle());
		System.out.println("Entry description: " + entry.getDescription().getText());
		
		System.out.println("Number of attachments downloaded = " + WebServiceClientUtil.extractFiles(stub, null));
		
		return entry;
	}

	public static void getFolderEntries(long binderId, int first, int max) throws Exception {
		TeamingServiceSoapBindingStub stub = getStubBasic();

		FolderEntryCollection result = stub.folder_getEntries(null, binderId, first, max);
		FolderEntryBrief[] entries = result.getEntries();
				
		System.out.println("Number of entries = " + entries.length);
		for(int i = 0; i < entries.length; i++) {
			System.out.println("(" + (i+1) + ") id=" + entries[i].getId() + ", title=" + entries[i].getTitle()); 
		}
	}

	public static void addFolderEntryByCopying(FolderEntry entry) throws Exception {
		TeamingServiceSoapBindingStub stub = getStubBasic();

		// We don't have to bother writing the code that copies the entry. 
		// All we have to do is to nullify the id field of the persistent entry
		// (actually we don't even have to do this), then simply re-use it
		// for add operation.
		
		entry.setTitle(entry.getTitle() + " (Copied)");
		entry.getDescription().setText(entry.getDescription().getText() + " (Copied)");
		
		File file = new File("C:/junk/junk1/debug.txt");
		WebServiceClientUtil.attachFile(stub, file);
		long entryId = stub.folder_addEntry(null, entry, "debug.txt");
		//long entryId = stub.folder_addEntry(null, entry, null);
		
		System.out.println("ID of the newly added entry: " + entryId);
	}

	public static void uploadFolderEntryFiles(long entryId) throws Exception {
		TeamingServiceSoapBindingStub stub = getStubBasic();

		File file = new File("C:/junk/junk1/Water lilies.jpg");		
		WebServiceClientUtil.attachFile(stub, file);
		stub.folder_uploadFile(null, entryId, "myPicture", "Jong Image.jpg");
		
		file = new File("C:/junk/junk1/Book1.xls");		
		WebServiceClientUtil.attachFile(stub, file);
		stub.folder_uploadFile(null, entryId, "myFile", "Jong Book.xls");
				
		System.out.println("Files uploaded for the entry : " + entryId);
	}

	public static void modifyFolderEntry(FolderEntry entry) throws Exception {
		TeamingServiceSoapBindingStub stub = getStubBasic();

		entry.setTitle(entry.getTitle() + " (Modified)");
		entry.getDescription().setText(entry.getDescription().getText() + " (Modified)");
		
		/*
		// Set all boolean fields to true
		for(int i=0; i<entry.getCustomBooleanFields().length; i++) {
			entry.getCustomBooleanFields()[i].setValue(Boolean.TRUE);			
		}
		// Set all date fields to current date/time
		for(int i=0; i<entry.getCustomDateFields().length; i++) {
			entry.getCustomDateFields()[i].setValue(Calendar.getInstance());			
		}
		// Append "(Modified)" to all string fields
		for(int i=0; i<entry.getCustomStringFields().length; i++) {
			entry.getCustomStringFields()[i].setValue(entry.getCustomStringFields()[i].getValue() + " (Modified)");			
		}
		// Shrink all long-array fields by one element (cut the last one).
		for(int i=0; i<entry.getCustomLongArrayFields().length; i++) {
			Long[] array = entry.getCustomLongArrayFields()[i].getValues();
			if(array.length > 0) {
				Long[] newArray = new Long[array.length-1];
				for(int j=0; j<newArray.length; j++)
					newArray[j] = array[j];
				
				entry.getCustomLongArrayFields()[i].setValues(newArray);							
			}
		}
		// Shrink all string-array fields by one element (cut the last one).
		for(int i=0; i<entry.getCustomStringArrayFields().length; i++) {
			String[] array = entry.getCustomStringArrayFields()[i].getValues();
			if(array.length > 0) {
				String[] newArray = new String[array.length-1];
				for(int j=0; j<newArray.length; j++)
					newArray[j] = array[j];
				
				entry.getCustomStringArrayFields()[i].setValues(newArray);							
			}
		}
		*/

		Calendar modificationTime = stub.folder_modifyEntry(null, entry);
		
		System.out.println("Modification time: " + modificationTime.getTime().toString());
	}
	public static Binder modifyBinder(Binder binder) throws Exception {
		TeamingServiceSoapBindingStub stub = getStubBasic();

		binder.setTitle(binder.getTitle() + " (Modified)");
		binder.getDescription().setText(binder.getDescription().getText() + " (Modified)");
		
		stub.binder_modifyBinder(null, binder);
		stub.binder_getBinder(null, binder.getId(), true);
		
		System.out.println("ID of the modified binder: " + binder.getId());
		return binder;
	}
	public static Binder uploadBinderFiles(Binder binder) throws Exception {
		TeamingServiceSoapBindingStub stub = getStubBasic();

		File file = new File("C:/junk/junk1/Water lilies.jpg");		
		WebServiceClientUtil.attachFile(stub, file);
		stub.binder_uploadFile(null, binder.getId(), "", "Jong Image.jpg"); //will add to attachments 
		
		file = new File("C:/junk/junk1/debug.txt");		
		WebServiceClientUtil.attachFile(stub, file);
		stub.binder_uploadFile(null, binder.getId(), "", "Jong Book.xls");
		binder = stub.binder_getBinder(null, binder.getId(), true);
		System.out.println("(WSS) Number of attachments downloaded = " + WebServiceClientUtil.extractFiles(stub, null));				
		System.out.println("Files uploaded for the binder : " + binder.getId());
		return binder;
	}

	public static void deleteFolderEntry(long entryId) throws Exception {
		TeamingServiceSoapBindingStub stub = getStubBasic();

		stub.folder_deleteEntry(null, entryId);
		
		System.out.println("ID of the deleted entry: " + entryId);
	}

	public static void getUser(long principalId) throws Exception {
		TeamingServiceSoapBindingStub stub = getStubBasic();
		
		User user = stub.profile_getUser(null, principalId, false);
		
		System.out.println("User title: " + user.getTitle());
	}

	public static void getGroup(long principalId) throws Exception {
		TeamingServiceSoapBindingStub stub = getStubBasic();
		
		Group group = stub.profile_getGroup(null, principalId, false);
		
		System.out.println("Group title: " + group.getTitle());
	}

	public static void getPrincipals(int first, int max) throws Exception {
		TeamingServiceSoapBindingStub stub = getStubBasic();

		PrincipalCollection result = stub.profile_getPrincipals(null, first, max);
		PrincipalBrief[] entries = result.getEntries();
				
		System.out.println("First = " + result.getFirst());
		System.out.println("Count = " + entries.length);
		System.out.println("Total = " + result.getTotal());
		for(int i = 0; i < entries.length; i++) {
			System.out.println("(" + i + ") id=" + entries[i].getId() + ", name=" + entries[i].getName() + ", type=" + entries[i].getType() + ", title=" + entries[i].getTitle() + ", email=" + entries[i].getEmailAddress()); 
		}
	}
	public static void checkUsers() throws Exception {
		TeamingServiceSoapBindingStub stub = getStubBasic();

		User testUser = new User();
		testUser.setName("jodi");
		testUser.setFirstName("Jodi");
		testUser.setMiddleName("Anne");
		testUser.setLastName("Tester");
		testUser.setEmailAddress("boulder@foo.bar");
		long testUserId = stub.profile_addUser(null, testUser, "changeIt");
		Long wsId = stub.profile_addUserWorkspace(null, testUserId);
		testUser = stub.profile_getUser(null, testUserId, false);
		if (!"Jodi Anne Tester".equals(testUser.getTitle())) System.out.println("Title not set");
		if (!wsId.equals(testUser.getWorkspaceId())) System.out.println("Workspace Id not set correctly");
		testUser.setZonName("jodi");
		stub.profile_modifyUser(null, testUser);
		testUser = stub.profile_getUser(null, testUserId, false);
		if (!"jodi".equals(testUser.getZonName())) System.out.println("Modify of zonName failed");
		try {
			testUser = uploadUserFile(testUser);
			Attachment[] atts = testUser.getAttachmentsField().getAttachments();
			stub.profile_removeFile(null, testUserId, atts[0].getFileName());
			testUser = stub.profile_getUserByName(null, "jodi", false);
			if (testUser.getAttachmentsField().getAttachments().length != atts.length-1) 
				System.out.println("removeFile failed");
		} finally {
			stub.profile_deletePrincipal(null, testUser.getId(), true);
		}
	}
	public static User uploadUserFile(User user) throws Exception {
		TeamingServiceSoapBindingStub stub = getStubBasic();

		File file = new File("C:/junk/junk1/Water lilies.jpg");		
		WebServiceClientUtil.attachFile(stub, file);
		stub.profile_uploadFile(null, user.getId(), "picture", "Jong Image.jpg"); //will add to attachments 
		System.out.println("Picture uploaded for the user : " + user.getId());
		
		user = stub.profile_getUser(null, user.getId(), true);
		System.out.println("(WSS) Number of attachments downloaded = " + WebServiceClientUtil.extractFiles(stub, null));				
		Attachment[] atts = user.getAttachmentsField().getAttachments();
		for (int i=0; i<atts.length; ++i) {
			System.out.println("Attachment: " + atts[i].getFileName() + " " + atts[i].getHref());
		}
		return user;
	}

	public static FileVersions getEntryFileVersions(long entryId, String fileName) throws Exception {
		TeamingServiceSoapBindingStub stub = getStubBasic();
		
		FileVersions fileVersions = stub.folder_getFileVersions(null, entryId, fileName);
		
		if(fileVersions != null) {
			System.out.println("File name: " + fileVersions.getFileName());
			FileVersion[] versions = fileVersions.getVersions();
			for(int i = 0; i < versions.length; i++)
				System.out.println("Version " + versions[i].getVersionNumber() + ": " + versions[i].getId());
		}
		else {
			System.out.println("No such file");
		}
		
		return fileVersions;
	}
	
	private static Long getGlobalWorkspace(TeamingServiceSoapBindingStub stub) throws Exception {
		
		String xml = stub.search_getWorkspaceTreeAsXML(null, -1, 2, "");
		try {
			Document document = DocumentHelper.parseText(xml);
			Element ws = (Element)document.getRootElement().selectSingleNode("./child[@title='Global Workspaces']");
			return Long.valueOf(ws.attributeValue("id"));
		} catch (DocumentException e) {
			System.out.println(e);
		}
		return null;
	}
	private static TemplateBrief getTemplateByName(TeamingServiceSoapBindingStub stub, String name) throws Exception {
		TemplateCollection templates = stub.template_getTemplates(null);
		TemplateBrief[] array = templates.getTemplates();
		for (int i=0; i<array.length; ++i) {
			TemplateBrief template = array[i];
			if (name.equals(template.getName())) return template;
		}
		return null;
	}
	private static Binder getTestFolder(String title) throws Exception {
		TeamingServiceSoapBindingStub stub = getStubBasic();

		long gblId = getGlobalWorkspace(stub);
		try {
			return stub.binder_getBinderByPathName(null, "/Workspaces/Global Workspaces/" + title, false);
		} catch (Exception ex) {
			TemplateBrief tb = getTemplateByName(stub, "_folder");
			return stub.binder_getBinder(null, stub.template_addBinder(null, gblId, tb.getId(), title), false);

		}
	}
	private static void checkGroups() throws Exception {
		TeamingServiceSoapBindingStub stub = getStubBasic();

		Group group = new Group();
		group.setName("testgroup");
		stub.profile_addGroup(null, group);
		group = stub.profile_getGroupByName(null, "testgroup", false);
		User testUser = getTestUser();
		stub.profile_addGroupMember(null, "testgroup", testUser.getName());
		PrincipalCollection members = stub.profile_getGroupMembers(null, "testgroup", 0, 0);
		PrincipalBrief[] entries = members.getEntries();
		
		System.out.println("First = " + members.getFirst());
		System.out.println("Count = " + entries.length);
		System.out.println("Total = " + members.getTotal());
		for(int i = 0; i < entries.length; i++) {
			System.out.println("(" + i + ") id=" + entries[i].getId() + ", name=" + entries[i].getName() + ", type=" + entries[i].getType() + ", title=" + entries[i].getTitle() + ", email=" + entries[i].getEmailAddress()); 
		}
		stub.profile_removeGroupMember(null, "testgroup", testUser.getName());
		members = stub.profile_getGroupMembers(null, "testgroup", 0, 0);
		entries = members.getEntries();
		System.out.println("First = " + members.getFirst());
		System.out.println("Count = " + entries.length);
		System.out.println("Total = " + members.getTotal());
		for(int i = 0; i < entries.length; i++) {
			System.out.println("(" + i + ") id=" + entries[i].getId() + ", name=" + entries[i].getName() + ", type=" + entries[i].getType() + ", title=" + entries[i].getTitle() + ", email=" + entries[i].getEmailAddress()); 
		}
		stub.profile_deletePrincipal(null, testUser.getId(), true);
		stub.profile_deletePrincipal(null, group.getId(), true);
	}
	public static User getTestUser() throws Exception {
		TeamingServiceSoapBindingStub stub = getStubBasic();

		User testUser =null;
		try {
			testUser = stub.profile_getUserByName(null, "jodi", false);
			System.out.println("jodi does not exist");
		} catch (Exception ex) {
			testUser = new User();
			testUser.setName("jodi");
			testUser.setFirstName("Jodi");
			testUser.setMiddleName("Anne");
			testUser.setLastName("Tester");
			testUser.setEmailAddress("boulder@foo.bar");
			long testUserId = stub.profile_addUser(null, testUser, "changeIt");
			testUser = stub.profile_getUser(null, testUserId, false);
		}
		return testUser;
	}
	
	public static void changeUserPassword(Long userId, String oldPassword, String newPassword) throws Exception {
		TeamingServiceSoapBindingStub stub = getStubBasic();

		stub.profile_changePassword(null, userId, oldPassword, newPassword);
	}
	
	public static void copyFolderEntry(long entryId, long destinationFolderId, boolean eventAsIcalString) throws Exception {
		TeamingServiceSoapBindingStub stub = getStubBasic();

		FolderEntry entry = stub.folder_getEntry(null, entryId, false, eventAsIcalString);
		System.out.println("Successfully fetched the entry");
		
		entry.setTitle(entry.getTitle() + " (Copied)");
		entry.setId(null);
		entry.setParentBinderId(destinationFolderId);
		long newEntryId = stub.folder_addEntry(null, entry, null);
		
		System.out.println("ID of the newly added entry: " + newEntryId);
	}

	protected static TeamingServiceSoapBindingStub getStubBasic() throws ServiceException {
		TeamingServiceSoapServiceLocator locator = new TeamingServiceSoapServiceLocator();
		locator.setTeamingServiceEndpointAddress(TEAMING_SERVICE_ADDRESS_BASIC);
		TeamingServiceSoapBindingStub stub = (TeamingServiceSoapBindingStub) locator.getTeamingService();
		stub._setProperty(org.apache.axis.AxisEngine.PROP_DOMULTIREFS, Boolean.FALSE);
		WebServiceClientUtil.setUserCredentialBasicAuth(stub, USERNAME, PASSWORD);
		return stub;
	}
	
	protected static TeamingServiceSoapBindingStub getStubWSS() throws ServiceException {
		EngineConfiguration config = WebServiceClientUtil.getMinimumEngineConfigurationWSSecurity();
		TeamingServiceSoapServiceLocator locator = new TeamingServiceSoapServiceLocator(config);
		locator.setTeamingServiceEndpointAddress(TEAMING_SERVICE_ADDRESS_WSS);
		TeamingServiceSoapBindingStub stub = (TeamingServiceSoapBindingStub) locator.getTeamingService();
		stub._setProperty(org.apache.axis.AxisEngine.PROP_DOMULTIREFS, Boolean.FALSE);
		WebServiceClientUtil.setUserCredentialWSSecurity(stub, USERNAME, PASSWORD, true);
		return stub;
	}
	
	public static void copyFileFromUserToEntry() throws Exception {
		TeamingServiceSoapBindingStub stub = getStubBasic();

		User admin = stub.profile_getUser(null, 1, false); 
		
		if(admin.getAttachmentsField() != null && admin.getAttachmentsField().getAttachments() != null &&
				admin.getAttachmentsField().getAttachments().length > 0) {
			Attachment attachment = admin.getAttachmentsField().getAttachments()[0];
			// Fetch the first attachment associated with this user's profile.
			byte[] fileContent = stub.profile_getAttachmentAsByteArray(null, 1, attachment.getId());
			// Upload the file as an attachment to the specific entry.
			stub.folder_uploadFileAsByteArray(null, 204, null, attachment.getFileName(), fileContent);
			System.out.println("Successfully copied");
		}
		else {
			System.out.println("This user doesn't have any attachment");
		}
	}
	
	private static void prettyPrintXML(Document doc) {
		OutputFormat format = OutputFormat.createPrettyPrint();
		try {
			XMLWriter writer = new XMLWriter(System.out, format);
			writer.write(doc);
		}
		catch(IOException e) {
			System.out.println(e);
		}
	}

	public static void addTaskEntry() throws Exception {
		TeamingServiceSoapBindingStub stub = getStubBasic();
		
	    FolderEntry fe = new FolderEntry();

		fe.setTitle("This task was added via web services");
		fe.setDescription(new Description(1,"Creating a task through web services"));
		fe.setParentBinderId(new Long(47)); // My task folder ID

		CustomStringArrayField[] allFields = new CustomStringArrayField[3];
		CustomStringArrayField status = new CustomStringArrayField("status",
				"selectbox", new String[] { "s2" });
		CustomStringArrayField priority = new CustomStringArrayField(
				"priority", "selectbox", new String[] { "p3" });
		CustomStringArrayField completed = new CustomStringArrayField(
				"completed", "selectbox", new String[] { "c030" });
		allFields[0] = status;
		allFields[1] = priority;
		allFields[2] = completed;
		fe.setCustomStringArrayFields(allFields);

		long entryId = stub.folder_addEntry(null, fe, null);
		
		System.out.println("Successfully created a task with ID = " + entryId);		
	}
	
	public static void getFunctionMembership() throws Exception {
		TeamingServiceSoapBindingStub stub = getStubBasic();
		long binderId = 251;
		FunctionMembership[] fma = stub.binder_getFunctionMembership(null, binderId);
		for(int i = 0; i < fma.length; i++) {
			FunctionMembership fm = fma[i];
			System.out.println("");
			System.out.println("Function Membership (" + i + ")");
			System.out.println("\tFunction Name: " + fm.getFunctionName());
			System.out.println("\tMember IDs: " + toString(fm.getMemberIds()));
			System.out.println("\tMember Names: " + toString(fm.getMemberNames()));
		}
	}
	
	public static void setFunctionMembership() throws Exception {
		TeamingServiceSoapBindingStub stub = getStubBasic();
		long binderId = 682;
		FunctionMembership fm = new FunctionMembership();
		fm.setFunctionName("__role.visitor");
		fm.setMemberIds(new Long[] {-1L});
		FunctionMembership[] fma = new FunctionMembership[]{fm};
		stub.binder_setFunctionMembership(null, binderId, fma);
	}
	
	public static void getMovedEntries() throws Exception {
		TeamingServiceSoapBindingStub stub = getStubBasic();
		long[] entryIds = stub.folder_getMovedEntries(null, null, Calendar.getInstance());
		System.out.println("Number of moved entries = " + entryIds.length);
		for(int i = 0; i < entryIds.length; i++)
			System.out.println("(" + i + ") ID = " + entryIds[i]);
	}
	
	public static void getDeletedAndRestoredEntries() throws Exception {
		TeamingServiceSoapBindingStub stub = getStubBasic();
		long[] folderIds = new long[] {51, 287};
		String family = "discussion";
		Calendar startTime = Calendar.getInstance();
		startTime.add(Calendar.MINUTE, -10);
		long[] deletedEntryIds = stub.folder_getDeletedEntriesInFolders(null, folderIds, family, startTime, Calendar.getInstance());
		System.out.println("Number of deleted entries = " + deletedEntryIds.length);
		for(int i = 0; i < deletedEntryIds.length; i++)
			System.out.println("(" + (i+1) + ") ID = " + deletedEntryIds[i]);
		long[] restoredEntryIds = stub.folder_getRestoredEntriesInFolders(null, folderIds, family, startTime, Calendar.getInstance());
		System.out.println("Number of restored entries = " + restoredEntryIds.length);
		for(int i = 0; i < restoredEntryIds.length; i++)
			System.out.println("(" + (i+1) + ") ID = " + restoredEntryIds[i]);
	}
	
	private static String toString(Object[] objs) {
		if(objs == null)
			return null;
		StringBuilder sb = new StringBuilder();
		for(Object obj:objs) {
			if(sb.length() > 0)
				sb.append(", ");
			sb.append(obj.toString());
		}
		return sb.toString();
	}
	
	public static void downloadSameFileMultipleTimes() throws Exception {
		// To measure download time
		TeamingServiceSoapBindingStub stub = getStubBasic();
		Long entryId = 123L;
		String attachmentId = "24e350ea3383b149013383dd2bf90025";
		System.out.println("Start time: " + new Date());
		for(int i = 0; i < 10; i++) {
			byte[] content = stub.folder_getAttachmentAsByteArray(null, entryId, attachmentId);
			System.out.println("(" + i + ") Downloaded file length: " + content.length);
		}
		System.out.println("End time: " + new Date());
	}
	
	public static void getTopWorkspaceIdRepeatedlyUsingMultipleThreads() throws Exception {
		int numThreads = 100;
		final int numIterations = 20;
		Thread[] threads = new Thread[numThreads];
		for (int i = 0; i < numThreads; i++) {
			final TeamingServiceSoapBindingStub stub = getStubWSS();
			threads[i] = new Thread("Client " + i) {
				@Override
				public void run() {
					for(int j = 0; j < numIterations; j++) {
						try {
							stub.binder_getTopWorkspaceId(null);
						} catch (RemoteException e) {
							System.out.println(e.toString());
						}
					}
					System.out.println("Thread [" + Thread.currentThread().getName() + "] completing normally");
				}
			};
		}
		for(int i = 0; i < numThreads; i++)
			threads[i].start();
		for(int i = 0; i < numThreads; i++)
			threads[i].join();
		System.out.println("getTopWorkspaceIdRepeatedlyUsingMultipleThreads completed");
	}
}
