# Thanks to Patrick Lightbody for submitting this...
#
# In your Quartz properties file, you'll need to set 
# org.quartz.jobStore.driverDelegateClass = org.quartz.impl.jdbcjobstore.PostreSQLDelegate

drop table SSQRTZ_job_listeners;
drop table SSQRTZ_trigger_listeners;
drop table SSQRTZ_fired_triggers;
DROP TABLE SSQRTZ_PAUSED_TRIGGER_GRPS;
DROP TABLE SSQRTZ_SCHEDULER_STATE;
DROP TABLE SSQRTZ_LOCKS;
drop table SSQRTZ_simple_triggers;
drop table SSQRTZ_cron_triggers;
DROP TABLE QRTZ_BLOB_TRIGGERS;
drop table SSQRTZ_triggers;
drop table SSQRTZ_job_details;
drop table SSQRTZ_calendars;

CREATE TABLE SSQRTZ_job_details
  (
    JOB_NAME  VARCHAR(100) NOT NULL,
    JOB_GROUP VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(250) NULL,
    JOB_CLASS_NAME   VARCHAR(250) NOT NULL, 
    IS_DURABLE BOOL NOT NULL,
    IS_VOLATILE BOOL NOT NULL,
    IS_STATEFUL BOOL NOT NULL,
    REQUESTS_RECOVERY BOOL NOT NULL,
    JOB_DATA BYTEA NULL,
    PRIMARY KEY (JOB_NAME,JOB_GROUP)
);

CREATE TABLE SSQRTZ_job_listeners
  (
    JOB_NAME  VARCHAR(100) NOT NULL, 
    JOB_GROUP VARCHAR(100) NOT NULL,
    JOB_LISTENER VARCHAR(100) NOT NULL,
    PRIMARY KEY (JOB_NAME,JOB_GROUP,JOB_LISTENER),
    FOREIGN KEY (JOB_NAME,JOB_GROUP) 
	REFERENCES SSQRTZ_JOB_DETAILS(JOB_NAME,JOB_GROUP) 
);

CREATE TABLE SSQRTZ_triggers
  (
    TRIGGER_NAME VARCHAR(100) NOT NULL,
    TRIGGER_GROUP VARCHAR(100) NOT NULL,
    JOB_NAME  VARCHAR(100) NOT NULL, 
    JOB_GROUP VARCHAR(100) NOT NULL,
    IS_VOLATILE BOOL NOT NULL,
    DESCRIPTION VARCHAR(250) NULL,
    NEXT_FIRE_TIME BIGINT NULL,
    PREV_FIRE_TIME BIGINT NULL,
    PRIORITY INTEGER NULL,
    TRIGGER_STATE VARCHAR(16) NOT NULL,
    TRIGGER_TYPE VARCHAR(8) NOT NULL,
    START_TIME BIGINT NOT NULL,
    END_TIME BIGINT NULL,
    CALENDAR_NAME VARCHAR(100) NULL,
    MISFIRE_INSTR SMALLINT NULL,
    JOB_DATA BYTEA NULL,
    PRIMARY KEY (TRIGGER_NAME,TRIGGER_GROUP),
    FOREIGN KEY (JOB_NAME,JOB_GROUP) 
	REFERENCES SSQRTZ_JOB_DETAILS(JOB_NAME,JOB_GROUP) 
);

CREATE TABLE SSQRTZ_simple_triggers
  (
    TRIGGER_NAME VARCHAR(100) NOT NULL,
    TRIGGER_GROUP VARCHAR(100) NOT NULL,
    REPEAT_COUNT BIGINT NOT NULL,
    REPEAT_INTERVAL BIGINT NOT NULL,
    TIMES_TRIGGERED BIGINT NOT NULL,
    PRIMARY KEY (TRIGGER_NAME,TRIGGER_GROUP),
    FOREIGN KEY (TRIGGER_NAME,TRIGGER_GROUP) 
	REFERENCES SSQRTZ_TRIGGERS(TRIGGER_NAME,TRIGGER_GROUP)
);

CREATE TABLE SSQRTZ_cron_triggers
  (
    TRIGGER_NAME VARCHAR(100) NOT NULL,
    TRIGGER_GROUP VARCHAR(100) NOT NULL,
    CRON_EXPRESSION VARCHAR(120) NOT NULL,
    TIME_ZONE_ID VARCHAR(80),
    PRIMARY KEY (TRIGGER_NAME,TRIGGER_GROUP),
    FOREIGN KEY (TRIGGER_NAME,TRIGGER_GROUP) 
	REFERENCES SSQRTZ_TRIGGERS(TRIGGER_NAME,TRIGGER_GROUP)
);

CREATE TABLE SSQRTZ_blob_triggers
  (
    TRIGGER_NAME VARCHAR(100) NOT NULL,
    TRIGGER_GROUP VARCHAR(100) NOT NULL,
    BLOB_DATA BYTEA NULL,
    PRIMARY KEY (TRIGGER_NAME,TRIGGER_GROUP),
    FOREIGN KEY (TRIGGER_NAME,TRIGGER_GROUP) 
        REFERENCES SSQRTZ_TRIGGERS(TRIGGER_NAME,TRIGGER_GROUP)
);

CREATE TABLE SSQRTZ_trigger_listeners
  (
    TRIGGER_NAME  VARCHAR(100) NOT NULL, 
    TRIGGER_GROUP VARCHAR(100) NOT NULL,
    TRIGGER_LISTENER VARCHAR(100) NOT NULL,
    PRIMARY KEY (TRIGGER_NAME,TRIGGER_GROUP,TRIGGER_LISTENER),
    FOREIGN KEY (TRIGGER_NAME,TRIGGER_GROUP) 
	REFERENCES SSQRTZ_TRIGGERS(TRIGGER_NAME,TRIGGER_GROUP)
);


CREATE TABLE SSQRTZ_calendars
  (
    CALENDAR_NAME  VARCHAR(100) NOT NULL, 
    CALENDAR BYTEA NOT NULL,
    PRIMARY KEY (CALENDAR_NAME)
);


CREATE TABLE SSQRTZ_paused_trigger_grps
  (
    TRIGGER_GROUP  VARCHAR(100) NOT NULL, 
    PRIMARY KEY (TRIGGER_GROUP)
);

CREATE TABLE SSQRTZ_fired_triggers 
  (
    ENTRY_ID VARCHAR(95) NOT NULL,
    TRIGGER_NAME VARCHAR(100) NOT NULL,
    TRIGGER_GROUP VARCHAR(100) NOT NULL,
    IS_VOLATILE BOOL NOT NULL,
    INSTANCE_NAME VARCHAR(100) NOT NULL,
    FIRED_TIME BIGINT NOT NULL,
    PRIORITY INTEGER NOT NULL,
    STATE VARCHAR(16) NOT NULL,
    JOB_NAME VARCHAR(100) NULL,
    JOB_GROUP VARCHAR(100) NULL,
    IS_STATEFUL BOOL NULL,
    REQUESTS_RECOVERY BOOL NULL,
    PRIMARY KEY (ENTRY_ID)
);

CREATE TABLE SSQRTZ_scheduler_state 
  (
    INSTANCE_NAME VARCHAR(100) NOT NULL,
    LAST_CHECKIN_TIME BIGINT NOT NULL,
    CHECKIN_INTERVAL BIGINT NOT NULL,
    PRIMARY KEY (INSTANCE_NAME)
);

CREATE TABLE SSQRTZ_locks
  (
    LOCK_NAME  VARCHAR(40) NOT NULL, 
    PRIMARY KEY (LOCK_NAME)
);


INSERT INTO SSQRTZ_locks values('TRIGGER_ACCESS');
INSERT INTO SSQRTZ_locks values('JOB_ACCESS');
INSERT INTO SSQRTZ_locks values('CALENDAR_ACCESS');
INSERT INTO SSQRTZ_locks values('STATE_ACCESS');
INSERT INTO SSQRTZ_locks values('MISFIRE_ACCESS');

commit;