connect sitescape/sitescape;
alter table SS_ZoneConfig add mobileAccessEnabled number(1,0);
alter table SS_AuditTrail add deletedFolderEntryFamily varchar2(32 char);
alter table SS_FolderEntries add preDeleted number(1,0);
alter table SS_FolderEntries add preDeletedWhen number(19,0);
alter table SS_FolderEntries add preDeletedBy number(19,0);
alter table SS_Forums add preDeleted number(1,0);
alter table SS_Forums add preDeletedWhen number(19,0);
alter table SS_Forums add preDeletedBy number(19,0);
alter table SS_Attachments add relevanceUUID varchar2(256 char);
alter table SS_Principals add diskSpaceUsed number(19,0);
alter table SS_Principals add diskQuota number(19,0);
alter table SS_Principals add maxGroupsQuota number(19,0);
alter table SS_ZoneConfig add diskQuotasEnabled number(1,0);
alter table SS_ZoneConfig add diskQuotaUserDefault number(10,0);
alter table SS_ZoneConfig add diskQuotasHighwaterPercentage number(10,0);
create table SS_Extensions (id char(32) not null, lockVersion number(19,0) not null, name varchar2(64 char), description varchar2(256 char), type number(10,0), author varchar2(255 char), authorEmail varchar2(255 char), authorSite varchar2(255 char), dateCreated varchar2(255 char), dateDeployed varchar2(255 char), zoneId number(19,0), primary key (id), unique (zoneId, name));
alter table SS_Extensions add title varchar2(255 char);
alter table SS_Extensions add version varchar2(255 char);
create table SS_SchemaInfo (schemaVersion number(19,0) not null, primary key (schemaVersion));
create index diskQuota_principal on SS_Principals (diskQuota);
create index internalId_Binder on SS_Forums (internalId);
create index internalId_Definition on SS_Definitions (internalId);
INSERT INTO SS_SchemaInfo values (5);