use sitescape;
alter table SS_Attachments drop constraint FKA1AD4C3193118767;
alter table SS_Attachments drop constraint FKA1AD4C31DB0761E4;
alter table SS_Attachments drop constraint FKA1AD4C31F93A11B4;
alter table SS_Dashboards drop constraint FKFA9653BE93118767;
alter table SS_Dashboards drop constraint FKFA9653BEDB0761E4;
alter table SS_Definitions drop constraint FK7B56F60193118767;
alter table SS_Definitions drop constraint FK7B56F601DB0761E4;
alter table SS_Events drop constraint FKDE0E53F893118767;
alter table SS_Events drop constraint FKDE0E53F8DB0761E4;
alter table SS_FolderEntries drop constraint FKA6632C83F7719C70;
alter table SS_FolderEntries drop constraint FKA6632C8393118767;
alter table SS_FolderEntries drop constraint FKA6632C83DB0761E4;
alter table SS_FolderEntries drop constraint FKA6632C83A3644438;
alter table SS_Forums drop constraint FKDF668A5193118767;
alter table SS_Forums drop constraint FKDF668A51DB0761E4;
alter table SS_Notifications drop constraint FK9131F9296EADA262;
alter table SS_PrincipalMembership drop constraint FK176F6225AEB5AABF;
alter table SS_Principals drop constraint FK7693816493118767;
alter table SS_Principals drop constraint FK76938164DB0761E4;
alter table SS_WorkflowStates drop constraint FK8FA8AA80A3644438;
alter table SS_Forums drop column upgradeVersion;
alter table SS_Attachments add zoneId numeric(19,0);
alter table SS_AuditTrail add zoneId numeric(19,0);
alter table SS_AuditTrail add applicationId numeric(19,0);
alter table SS_CustomAttributes add zoneId numeric(19,0);
alter table SS_Dashboards add zoneId numeric(19,0);
alter table SS_Definitions add binderId numeric(19,0);
create table SS_EmailAddresses (principal numeric(19,0) not null, type varchar(64) not null, zoneId numeric(19,0) not null, address nvarchar(256) null, primary key (principal, type));
alter table SS_Events add zoneId numeric(19,0);
alter table SS_Events add calUid nvarchar(255);
alter table SS_Events add freeBusy varchar(32);
alter table SS_FolderEntries add zoneId numeric(19,0);
alter table SS_FolderEntries add subscribed tinyint;
alter table SS_Forums add branding text;
alter table SS_Forums add postingEnabled tinyint;
alter table SS_Functions add internalId varchar(32);
alter table SS_Functions add zoneWide tinyint;
create table SS_IndexNode (id char(32) not null, nodeName varchar(128) null, indexName varchar(160) null, zoneId numeric(19,0) null, accessMode varchar(16) null, inSynch tinyint null, primary key (id), unique (nodeName, indexName));
create table SS_IndexingJournal (id numeric(19,0) identity not null, zoneId numeric(19,0) null, nodeName varchar(128) null, indexName varchar(160) null, operationName varchar(32) null, operationArgs image null, primary key (id));
create table SS_LdapConnectionConfig (id char(32) not null, zoneId numeric(19,0) null, url nvarchar(255) null, userIdAttribute nvarchar(255) null, mappings ntext null, userSearches ntext null, groupSearches ntext null, principal nvarchar(255) null, credentials nvarchar(255) null, position int null, primary key (id));
alter table SS_LibraryEntries add zoneId numeric(19,0);
create table SS_NotifyStatus (ownerId numeric(19,0) not null, zoneId numeric(19,0) null, ownerType varchar(16) null, owningBinderKey varchar(255) null, owningBinderId numeric(19,0) null, lastModified datetime null, lastDigestSent datetime null, lastFullSent datetime null, primary key (ownerId));
alter table SS_Postings add credentials varchar(64);
alter table SS_Principals add skypeId nvarchar(64);
alter table SS_Principals add twitterId nvarchar(64);
alter table SS_Principals add status nvarchar(256);
alter table SS_Principals add statusDate datetime;
alter table SS_Principals add miniBlogId numeric(19,0);
alter table SS_Principals add postUrl nvarchar(256);
alter table SS_Principals add timeout int;
alter table SS_Principals add trusted tinyint;
alter table SS_Principals add maxIdleTime int;
alter table SS_Principals add sameAddrPolicy tinyint;
alter table SS_Ratings add zoneId numeric(19,0);
alter table SS_SeenMap add zoneId numeric(19,0);
create table SS_SharedEntity (id char(32) not null, referer numeric(19,0) null, zoneId numeric(19,0) null, sharedDate datetime null, accessId numeric(19,0) null, accessType numeric(19,0) null, entityType varchar(16) null, entityId numeric(19,0) null, primary key (id));
create table SS_SimpleName (zoneId numeric(19,0) not null, name nvarchar(128) not null, emailAddress varchar(128) null, binderId numeric(19,0) null, binderType varchar(16) null, primary key (zoneId, name));
alter table SS_Subscriptions add zoneId numeric(19,0);
alter table SS_Subscriptions add encodedStyles varchar(256);
alter table SS_Tags add zoneId numeric(19,0);
create table SS_TokenInfo (id char(32) not null, type char(1) not null, zoneId numeric(19,0) null, seed varchar(128) null, userId numeric(19,0) null, applicationId numeric(19,0) null, binderId numeric(19,0) null, binderAccessConstraints int null, clientAddr varchar(128) null, lastAccessTime datetime null, primary key (id));
alter table SS_UserProperties add zoneId numeric(19,0);
create table SS_WorkflowHistory (id char(32) not null, zoneId numeric(19,0) null, startBy numeric(19,0) null, startDate datetime null, endBy numeric(19,0) null, endDate datetime null, entityId numeric(19,0) null, entityType varchar(16) null, owningBinderId numeric(19,0) null, owningBinderKey varchar(255) null, tokenId numeric(19,0) null, state nvarchar(64) null, threadName nvarchar(64) null, definitionId varchar(32) null, ended tinyint null, primary key (id));
alter table SS_WorkflowResponses add zoneId numeric(19,0);
alter table SS_WorkflowStates add zoneId numeric(19,0);
create table SS_ZoneConfig (zoneId numeric(19,0) not null, upgradeVersion int null, postingEnabled tinyint null, simpleUrlPostingEnabled tinyint null, sendMailEnabled tinyint null, allowLocalLogin tinyint null, allowAnonymousAccess tinyint null, allowSelfRegistration tinyint null, lastUpdate numeric(19,0) null, primary key (zoneId));
create table SS_ZoneInfo (id char(32) not null, zoneId numeric(19,0) not null unique, zoneName nvarchar(128) not null unique, virtualHost nvarchar(255) null unique, primary key (id));
alter table SS_Attachments add constraint FKA1AD4C3158C1A25C foreign key (creation_principal) references SS_Principals;
alter table SS_Attachments add constraint FKA1AD4C31A0B77CD9 foreign key (modification_principal) references SS_Principals;
alter table SS_Attachments add constraint FKA1AD4C31BEEA2CA9 foreign key (filelock_owner) references SS_Principals;
alter table SS_Dashboards add constraint FKFA9653BE58C1A25C foreign key (creation_principal) references SS_Principals;
alter table SS_Dashboards add constraint FKFA9653BEA0B77CD9 foreign key (modification_principal) references SS_Principals;
alter table SS_Definitions add constraint FK7B56F60158C1A25C foreign key (creation_principal) references SS_Principals;
alter table SS_Definitions add constraint FK7B56F601A0B77CD9 foreign key (modification_principal) references SS_Principals;
alter table SS_EmailAddresses add constraint FKC706C3457488E8C7 foreign key (principal) references SS_Principals on delete cascade;
alter table SS_Events add constraint FKDE0E53F858C1A25C foreign key (creation_principal) references SS_Principals;
alter table SS_Events add constraint FKDE0E53F8A0B77CD9 foreign key (modification_principal) references SS_Principals;
alter table SS_FolderEntries add constraint FKA6632C83BD21B765 foreign key (reserved_principal) references SS_Principals;
alter table SS_FolderEntries add constraint FKA6632C8358C1A25C foreign key (creation_principal) references SS_Principals;
alter table SS_FolderEntries add constraint FKA6632C83A0B77CD9 foreign key (modification_principal) references SS_Principals;
alter table SS_FolderEntries add constraint FKA6632C8369145F2D foreign key (wrk_principal) references SS_Principals;
alter table SS_Forums add constraint FKDF668A5158C1A25C foreign key (creation_principal) references SS_Principals;
alter table SS_Forums add constraint FKDF668A51A0B77CD9 foreign key (modification_principal) references SS_Principals;
alter table SS_Notifications add constraint FK9131F929345DBD57 foreign key (principalId) references SS_Principals;
alter table SS_PrincipalMembership add constraint FK176F6225A3FFCD99 foreign key (userId) references SS_Principals;
alter table SS_PrincipalMembership add constraint FK176F622542AEEC1E foreign key (groupId) references SS_Principals;
alter table SS_PrincipalMembership add constraint FK176F62257465C5B4 foreign key (userId) references SS_Principals;
alter table SS_Principals add constraint FK7693816458C1A25C foreign key (creation_principal) references SS_Principals;
alter table SS_Principals add constraint FK76938164A0B77CD9 foreign key (modification_principal) references SS_Principals;
alter table SS_SharedEntity add constraint FK93426C47F68E5AD foreign key (referer) references SS_Principals;
alter table SS_WorkflowStates add constraint FK8FA8AA8069145F2D foreign key (wrk_principal) references SS_Principals;
alter table SSQRTZ_TRIGGERS add PRIORITY integer null;
alter table SSQRTZ_TRIGGERS add JOB_DATA image null;
alter table SSQRTZ_FIRED_TRIGGERS add PRIORITY integer null;
alter table SSQRTZ_SCHEDULER_STATE drop column RECOVERER;
alter table SS_Events alter column timeZone varchar(80);
create index owningBinder_audit on SS_AuditTrail (owningBinderId);
create index entityOwner_audit on SS_AuditTrail (entityId, entityType);
create index entityTransaction_audit on SS_AuditTrail (startDate, entityId, entityType, transactionType);
create index owningBinder_clog on SS_ChangeLogs (owningBinderId);
create index entityOwner_clog on SS_ChangeLogs (entityId, entityType);
create index address_email on SS_EmailAddresses (address);
create index indexingJournal_nodeIndex on SS_IndexingJournal (nodeName, indexName);
create index notifyStatus_full on SS_NotifyStatus (zoneId, lastModified, lastFullSent);
create index notifyStatus_digest on SS_NotifyStatus (zoneId, lastModified, lastDigestSent);
create index access_shared on SS_SharedEntity (sharedDate, accessId, accessType);
create index binderId_simpleName on SS_SimpleName (binderId);
create index emailAddress_simpleName on SS_SimpleName (emailAddress);
create index userId_tokenInfoSession on SS_TokenInfo (userId);
create index owningBinder_wfhistory on SS_WorkflowHistory (owningBinderId);
create index entityTransaction_wfhistory on SS_WorkflowHistory (startDate, entityId, entityType);
create index entityOwner_wfhistory on SS_WorkflowHistory (entityId, entityType);
create unique index definition_name on SS_Definitions (zoneId, name, binderId);
go
update SSQRTZ_TRIGGERS set PRIORITY=5 where PRIORITY is null;
update SSQRTZ_FIRED_TRIGGERS set PRIORITY=5 where PRIORITY is null;
