tinyMCE.addI18n('fi.ss_addimage_dlg',{
tab_general:"Yleistä",
tab_appearance:"Ulkoasu",
tab_advanced:"Lisäasetukset",
general:"Yleistä",
title:"Otsikko",
preview:"Esikatselu",
constrain_proportions:"Rajauksen suhteet",
langdir:"Kielen kirjoitussuunta",
langcode:"Kielikoodi",
long_desc:"Linkki pitkään kuvaukseen",
style:"Tyyli",
classes:"Luokat",
ltr:"Vasemmalta oikealle",
rtl:"Oikealta vasemmalle",
id:"Tunnus",
map:"Kuvakartta",
swap_image:"Vaihda kuva",
alt_image:"Vaihtoehtoinen kuva",
mouseover:"kun osoitin on kohdalla",
mouseout:"kun osoitin siirretään pois",
misc:"Muuta",
example_img:"Ulkoasun esikatselukuva",
missing_alt:"Haluatko varmasti jatkaa ilman kuvatekstiä? Kuva ei ole ehkä sellaisten henkilöiden käytettävissä, joilla on rajoitteita tai jotka käyttävät tekstipohjaista selainta tai selaavat verkkoa siten, että kuvat on poistettu käytöstä.",
dialog_title:"Lisää/muokkaa kuvaa",
src:"Kuvan URL",
alt:"Kuvateksti",
list:"Kuvaluettelo",
border:"Reuna",
dimensions:"Koko",
vspace:"Pystysuuntainen väli",
hspace:"Vaakasuuntainen väli",
align:"Tasaus",
align_baseline:"Perusviiva",
align_top:"Ylä",
align_middle:"Keski",
align_bottom:"Ala",
align_texttop:"Tekstin yläreuna",
align_textbottom:"Tekstin alareuna",
align_left:"Vasen",
align_right:"Oikea",
image_list:"Kuvaluettelo"
});