/**
 * 
 */
package com.sitescape.team.util;

import java.util.Observer;

/**
 * @author dml
 * 
 * An interface for {@link Object}s which register for events generated by an
 * {@link EventSource}. This interface is very similar to {@link Observer} but
 * uses generics to maintain type-safety.
 * 
 * @param <S> -
 *            the type of {@link EventSource} this <code>EventListener</code>
 *            is for
 */
public interface EventListener<S extends EventSource<S, E>, E> extends
		java.util.EventListener {

	public void onNotification(S source, E event);

}
