use sitescape;
alter table SS_ZoneConfig add column mobileAccessEnabled bit;
alter table SS_AuditTrail add column deletedFolderEntryFamily varchar(32);
alter table SS_FolderEntries add column preDeleted bit;
alter table SS_FolderEntries add column preDeletedWhen bigint;
alter table SS_FolderEntries add column preDeletedBy bigint;
alter table SS_Forums add column preDeleted bit;
alter table SS_Forums add column preDeletedWhen bigint;
alter table SS_Forums add column preDeletedBy bigint;
alter table SS_Attachments add column relevanceUUID varchar(256);
alter table SS_Principals add column diskSpaceUsed bigint;
alter table SS_Principals add column diskQuota bigint;
alter table SS_Principals add column maxGroupsQuota bigint;
alter table SS_ZoneConfig add column diskQuotasEnabled bit;
alter table SS_ZoneConfig add column diskQuotaUserDefault integer;
alter table SS_ZoneConfig add column diskQuotasHighwaterPercentage integer;
create table SS_Extensions (id char(32) not null, lockVersion bigint not null, name varchar(64), description varchar(256), type integer, author varchar(255), authorEmail varchar(255), authorSite varchar(255), dateCreated varchar(255), dateDeployed varchar(255), zoneId bigint, primary key (id), unique (zoneId, name)) ENGINE=InnoDB;
alter table SS_Extensions add column title varchar(255);
alter table SS_Extensions add column version varchar(255);
create table SS_SchemaInfo (schemaVersion bigint not null, primary key (schemaVersion)) ENGINE=InnoDB;
create index diskQuota_principal on SS_Principals (diskQuota);
create index internalId_Binder on SS_Forums (internalId);
create index internalId_Definition on SS_Definitions (internalId);
INSERT INTO SS_SchemaInfo values (5);