use sitescape;
DROP INDEX entityOwner_clog on SS_ChangeLogs;
DROP INDEX entityOwner_audit ON SS_AuditTrail;
DROP INDEX entityTransaction_audit ON SS_AuditTrail;
ALTER TABLE SS_Events MODIFY dtStart datetime null DEFAULT null;
ALTER TABLE SS_Events add dtCalcStart datetime;
ALTER TABLE SS_Events add dtCalcEnd datetime;
create table SS_EmailLog (id char(32) not null, zoneId bigint, sendDate datetime not null, fromField varchar(255), subj varchar(255), comment longtext, status varchar(16) not null, type varchar(32) not null, toEmailAddresses longtext, fileAttachments longtext, primary key (id)) ENGINE=InnoDB;
create index index_emaillog on SS_EmailLog (sendDate, status, type);
create table SS_FunctionConditionMap (functionId bigint not null, meet varchar(16), conditionId bigint) ENGINE=InnoDB;
create table SS_FunctionConditions (id bigint not null auto_increment, type varchar(32) not null, zoneId bigint not null, encodedSpec longtext, title varchar(255) not null, description_text longtext, description_format integer, primary key (id)) ENGINE=InnoDB;
alter table SS_FunctionConditionMap add constraint FK945D2AD8BCA364AE foreign key (functionId) references SS_Functions (id);
alter table SS_FunctionConditionMap add constraint FK945D2AD868DAC30E foreign key (conditionId) references SS_FunctionConditions (id);
create table SS_BinderQuota (binderId bigint not null, zoneId bigint not null, diskQuota bigint, diskSpaceUsed bigint, diskSpaceUsedCumulative bigint, primary key (binderId)) ENGINE=InnoDB;
create index diskSpaceUsed_bquota on SS_BinderQuota (diskSpaceUsed);
create index diskSpaceUsedCumulative_bquota on SS_BinderQuota (diskSpaceUsedCumulative);
create index diskQuota_bquota on SS_BinderQuota (diskQuota);
alter table SS_ZoneConfig add column binderQuotasInitialized bit;
alter table SS_ZoneConfig add column binderQuotasEnabled bit;
alter table SS_ZoneConfig add column binderQuotasAllowOwner bit;
CREATE INDEX entityOwner_clog on SS_ChangeLogs (entityType, entityId);
CREATE INDEX operationDate_clog on SS_ChangeLogs (operationDate);
CREATE INDEX entityOwner_audit on SS_AuditTrail (entityType, entityId);
CREATE INDEX startDate_audit ON SS_AuditTrail (startDate);
CREATE INDEX startBy_audit ON SS_AuditTrail (startBy);
INSERT INTO SS_SchemaInfo values (18);