use sitescape;
DROP INDEX entityOwner_clog on SS_ChangeLogs;
DROP INDEX entityOwner_audit ON SS_AuditTrail;
DROP INDEX entityTransaction_audit ON SS_AuditTrail;
ALTER TABLE SS_Events ALTER COLUMN dtStart datetime null;
ALTER TABLE SS_Events add dtCalcStart datetime null;
ALTER TABLE SS_Events add dtCalcEnd datetime null;
create table SS_EmailLog (id char(32) not null, zoneId numeric(19,0) null, sendDate datetime not null, fromField nvarchar(255) null, subj nvarchar(255) null, comment ntext null, status varchar(16) not null, type varchar(32) not null, toEmailAddresses ntext null, fileAttachments ntext null, primary key (id));
create index index_emaillog on SS_EmailLog (sendDate, status, type);
create table SS_FunctionConditionMap (functionId numeric(19,0) not null, meet varchar(16) null, conditionId numeric(19,0) null);
create table SS_FunctionConditions (id numeric(19,0) identity not null, type varchar(32) not null, zoneId numeric(19,0) not null, encodedSpec ntext null, title nvarchar(255) not null, description_text ntext null, description_format int null, primary key (id));
alter table SS_FunctionConditionMap add constraint FK945D2AD8BCA364AE foreign key (functionId) references SS_Functions;
alter table SS_FunctionConditionMap add constraint FK945D2AD868DAC30E foreign key (conditionId) references SS_FunctionConditions;
create table SS_BinderQuota (binderId numeric(19,0) not null, zoneId numeric(19,0) not null, diskQuota numeric(19,0) null, diskSpaceUsed numeric(19,0) null, diskSpaceUsedCumulative numeric(19,0) null, primary key (binderId));
create index diskSpaceUsed_bquota on SS_BinderQuota (diskSpaceUsed);
create index diskSpaceUsedCumulative_bquota on SS_BinderQuota (diskSpaceUsedCumulative);
create index diskQuota_bquota on SS_BinderQuota (diskQuota);
alter table SS_ZoneConfig add binderQuotasInitialized tinyint;
alter table SS_ZoneConfig add binderQuotasEnabled tinyint;
alter table SS_ZoneConfig add binderQuotasAllowOwner tinyint;
alter table SS_ZoneConfig add holidays varchar(4096) null;
alter table SS_ZoneConfig add weekendDays varchar(128) null;
CREATE INDEX entityOwner_clog on SS_ChangeLogs (entityType, entityId);
CREATE INDEX operationDate_clog on SS_ChangeLogs (operationDate);
CREATE INDEX entityOwner_audit on SS_AuditTrail (entityType, entityId);
CREATE INDEX startDate_audit ON SS_AuditTrail (startDate);
CREATE INDEX startBy_audit ON SS_AuditTrail (startBy);
INSERT INTO SS_SchemaInfo values (18);