connect sitescape/sitescape;
DROP INDEX entityOwner_clog;
DROP INDEX entityOwner_audit;
DROP INDEX entityTransaction_audit;
DROP INDEX internalId_Definition;
DROP INDEX diskQuota_principal; 
DROP INDEX entityTransaction_wfhistory;
DROP INDEX access_shared;
ALTER TABLE SS_Events MODIFY dtStart timestamp null;
ALTER TABLE SS_Events add dtCalcStart timestamp;
ALTER TABLE SS_Events add dtCalcEnd timestamp;
create table SS_EmailLog (id char(32) not null, zoneId number(19,0), sendDate timestamp not null, fromField varchar2(255 char), subj varchar2(255 char), comment clob, status varchar2(16 char) not null, type varchar2(32 char) not null, toEmailAddresses clob, fileAttachments clob, primary key (id));
create index index_emaillog on SS_EmailLog (sendDate, status, type);
create table SS_FunctionConditionMap (functionId number(19,0) not null, meet varchar2(16 char), conditionId number(19,0));
create table SS_FunctionConditions (id number(19,0) not null, type varchar2(32 char) not null, zoneId number(19,0) not null, encodedSpec clob, title varchar2(255 char) not null, description_text clob, description_format number(10,0), primary key (id));
alter table SS_FunctionConditionMap add constraint FK945D2AD8BCA364AE foreign key (functionId) references SS_Functions;
alter table SS_FunctionConditionMap add constraint FK945D2AD868DAC30E foreign key (conditionId) references SS_FunctionConditions;
create table SS_BinderQuota (binderId number(19,0) not null, zoneId number(19,0) not null, diskQuota number(19,0), diskSpaceUsed number(19,0), diskSpaceUsedCumulative number(19,0), primary key (binderId));
alter table SS_ZoneConfig add binderQuotasInitialized number(1,0);
alter table SS_ZoneConfig add binderQuotasEnabled number(1,0);
alter table SS_ZoneConfig add binderQuotasAllowOwner number(1,0);
alter table SS_ZoneConfig add holidays varchar2(4096);
alter table SS_ZoneConfig add weekendDays varchar2(128);
CREATE INDEX entityOwner_clog on SS_ChangeLogs (entityType, entityId);
CREATE INDEX operationDate_clog on SS_ChangeLogs (zoneId, operationDate);
CREATE INDEX entityOwner_audit on SS_AuditTrail (entityType, entityId);
CREATE INDEX search_audit ON SS_AuditTrail (zoneId, startDate, startBy);
CREATE INDEX internal_Binder ON SS_Forums (zoneId, internalId);
CREATE INDEX binder_Dash ON SS_Dashboards (binderId);
CREATE INDEX internal_Definition ON SS_Definitions (zoneId, internalId, type);
CREATE INDEX sendDate_emaillog ON SS_EmailLog (zoneId, sendDate);
CREATE INDEX entryDef_fEntry ON SS_FolderEntries (entryDef);
CREATE INDEX snapshot_lstats ON SS_LicenseStats (zoneId, snapshotDate);
CREATE INDEX email_postings ON SS_Postings (zoneId, emailAddress);
CREATE INDEX internal_principal ON SS_Principals (zoneId,internalId);
CREATE INDEX type_principal ON SS_Principals (zoneId, type);
CREATE INDEX entryDef_principal ON SS_Principals (entryDef);
CREATE INDEX access_shared ON SS_SharedEntity (accessType, accessId, sharedDate);
CREATE INDEX entity_shared ON SS_SharedEntity (entityType, entityId);
CREATE INDEX entity_tag ON SS_Tags (entity_type, entity_id);
CREATE INDEX owner_tag ON SS_Tags (owner_type, owner_id);
CREATE INDEX startDate_wfhistory ON SS_WorkflowHistory (zoneId, startDate);
CREATE INDEX entity_Ratings ON SS_Ratings (entityId, entityType);
CREATE INDEX entity_Subscriptions ON SS_Subscriptions (entityId, entityType);
alter table SS_SeenMap add pruneDays number(19,0);
INSERT INTO SS_SchemaInfo values (20);