use sitescape;
DROP INDEX entityOwner_clog on SS_ChangeLogs;
DROP INDEX entityOwner_audit ON SS_AuditTrail;
DROP INDEX entityTransaction_audit ON SS_AuditTrail;
DROP INDEX internalId_Definition ON SS_Definitions;
DROP INDEX diskQuota_principal ON SS_Principals; 
DROP INDEX entityTransaction_wfhistory ON SS_WorkflowHistory;
DROP INDEX access_shared ON SS_SharedEntity;
ALTER TABLE SS_Events MODIFY dtStart datetime null DEFAULT null;
ALTER TABLE SS_Events add dtCalcStart datetime;
ALTER TABLE SS_Events add dtCalcEnd datetime;
create table SS_EmailLog (id char(32) not null, zoneId bigint, sendDate datetime not null, fromField varchar(255), subj varchar(255), comment longtext, status varchar(16) not null, type varchar(32) not null, toEmailAddresses longtext, fileAttachments longtext, primary key (id)) ENGINE=InnoDB;
create index index_emaillog on SS_EmailLog (sendDate, status, type);
create table SS_FunctionConditionMap (functionId bigint not null, meet varchar(16), conditionId bigint) ENGINE=InnoDB;
create table SS_FunctionConditions (id bigint not null auto_increment, type varchar(32) not null, zoneId bigint not null, encodedSpec longtext, title varchar(255) not null, description_text longtext, description_format integer, primary key (id)) ENGINE=InnoDB;
alter table SS_FunctionConditionMap add constraint FK945D2AD8BCA364AE foreign key (functionId) references SS_Functions (id);
alter table SS_FunctionConditionMap add constraint FK945D2AD868DAC30E foreign key (conditionId) references SS_FunctionConditions (id);
create table SS_BinderQuota (binderId bigint not null, zoneId bigint not null, diskQuota bigint, diskSpaceUsed bigint, diskSpaceUsedCumulative bigint, primary key (binderId)) ENGINE=InnoDB;
alter table SS_ZoneConfig add column binderQuotasInitialized bit;
alter table SS_ZoneConfig add column binderQuotasEnabled bit;
alter table SS_ZoneConfig add column binderQuotasAllowOwner bit;
alter table SS_ZoneConfig add column holidays varchar(4096);
alter table SS_ZoneConfig add column weekendDays varchar(128);
CREATE INDEX entityOwner_clog on SS_ChangeLogs (entityType, entityId);
CREATE INDEX operationDate_clog on SS_ChangeLogs (zoneId, operationDate);
CREATE INDEX entityOwner_audit on SS_AuditTrail (entityType, entityId);
CREATE INDEX search_audit ON SS_AuditTrail (zoneId, startDate, startBy);
CREATE INDEX internal_Binder ON SS_Forums (zoneId, internalId);
CREATE INDEX binder_Dash ON SS_Dashboards (binderId);
CREATE INDEX internal_Definition ON SS_Definitions (zoneId, internalId, type);
CREATE INDEX sendDate_emaillog ON SS_EmailLog (zoneId, sendDate);
CREATE INDEX entryDef_fEntry ON SS_FolderEntries (entryDef);
CREATE INDEX snapshot_lstats ON SS_LicenseStats (zoneId, snapshotDate);
CREATE INDEX email_postings ON SS_Postings (zoneId, emailAddress);
CREATE INDEX internal_principal ON SS_Principals (zoneId,internalId);
CREATE INDEX type_principal ON SS_Principals (zoneId, type);
CREATE INDEX entryDef_principal ON SS_Principals (entryDef);
CREATE INDEX access_shared ON SS_SharedEntity (accessType, accessId, sharedDate);
CREATE INDEX entity_shared ON SS_SharedEntity (entityType, entityId);
CREATE INDEX entity_tag ON SS_Tags (entity_type, entity_id);
CREATE INDEX owner_tag ON SS_Tags (owner_type, owner_id);
CREATE INDEX startDate_wfhistory ON SS_WorkflowHistory (zoneId, startDate);
CREATE INDEX entity_Ratings ON SS_Ratings (entityId, entityType);
CREATE INDEX entity_Subscriptions ON SS_Subscriptions (entityId, entityType);
alter table SS_SeenMap add pruneDays bigint;
INSERT INTO SS_SchemaInfo values (20);